### ISSUE TITLE
Can't run Docker image, error: no such file or directory, open './.env'

### ISSUE THREAD

**Issue by Kovah** [tellform/docker_files#3]
Sadly I wasn't able to get the Docker image running despite the documentation requires only three steps.

1. Cloned the repo
2. Made a copy of the .env.dist file (`cp .env.dist .env`) and modified it to match my setup
3. Run `docker-compose up -d`

The following output is thrown at me.

```
tellform_1  | { Error: ENOENT: no such file or directory, open './.env'
tellform_1  |     at Error (native)
tellform_1  |     at Object.fs.openSync (fs.js:642:18)
tellform_1  |     at Object.fs.readFileSync (fs.js:510:33)
tellform_1  |     at Object.config (/opt/tellform/node_modules/dotenv/lib/main.js:30:37)
tellform_1  |     at Object.<anonymous> (/opt/tellform/server.js:6:19)
tellform_1  |     at Module._compile (module.js:570:32)
tellform_1  |     at Object.Module._extensions..js (module.js:579:10)
tellform_1  |     at Module.load (module.js:487:32)
tellform_1  |     at tryModuleLoad (module.js:446:12)
tellform_1  |     at Function.Module._load (module.js:438:3) errno: -2, code: 'ENOENT', syscall: 'open', path: './.env' }
tellform_1  |
tellform_1  | /opt/tellform/node_modules/mongoose/node_modules/mongodb/lib/db.js:1712
tellform_1  |     if(databaseName.indexOf(invalidChars[i]) != -1) throw MongoError.create({message: "database names cannot contain the character '" + invalidChars[i] + "'", driver:true});
tellform_1  |                                                     ^
tellform_1  | MongoError: database names cannot contain the character ' '
tellform_1  |     at Function.MongoError.create (/opt/tellform/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
tellform_1  |     at validateDatabaseName (/opt/tellform/node_modules/mongoose/node_modules/mongodb/lib/db.js:1712:70)
tellform_1  |     at new Db (/opt/tellform/node_modules/mongoose/node_modules/mongodb/lib/db.js:137:3)
tellform_1  |     at NativeConnection.doOpen (/opt/tellform/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:53:15)
tellform_1  |     at NativeConnection.Connection._open (/opt/tellform/node_modules/mongoose/lib/connection.js:470:15)
tellform_1  |     at /opt/tellform/node_modules/mongoose/lib/connection.js:283:11
tellform_1  |     at new Promise.ES6 (/opt/tellform/node_modules/mongoose/lib/promise.js:45:3)
tellform_1  |     at NativeConnection.Connection.open (/opt/tellform/node_modules/mongoose/lib/connection.js:282:10)
tellform_1  |     at Mongoose.connect (/opt/tellform/node_modules/mongoose/lib/index.js:241:47)
tellform_1  |     at Object.<anonymous> (/opt/tellform/server.js:26:19)
tellform_1  |     at Module._compile (module.js:570:32)
tellform_1  |     at Object.Module._extensions..js (module.js:579:10)
tellform_1  |     at Module.load (module.js:487:32)
tellform_1  |     at tryModuleLoad (module.js:446:12)
tellform_1  |     at Function.Module._load (module.js:438:3)
tellform_1  |     at Module.runMain (module.js:604:10)
tellform_tellform_1 exited with code 1
```

And yes, the `.env` file is present, readable and properly configured.

**Comment by bpeynet** [comment]
Because of this line in `.env`,
`MONGODB_URI=mongodb://mongo/tellform #DO NOT CHANGE`
docker puts the comment into the variable, with the spaces it contains.
So remove the comment :
`MONGODB_URI=mongodb://mongo/tellform`

**Comment by Deliaz** [comment]
I have the exact same problem. (I am running macOS).
Tried to clean env from `#DO NOT CHANGE` and it doesn't work. 

Btw, this issue looks similar: #1

**Comment by scleriot** [comment]
I managed to get it working, the changes I made are available here: https://github.com/tellform/docker_files/pull/4

**Comment by spkjess** [comment]
@Kovah this issue can be closed yes?

**Comment by Kovah** [comment]
Never tried Tellform since, but from the user comments this seems solved.

**Comment by peteristhegreat** [comment]
Note that for some projects, they have a `.env.example` file that needs to be renamed to `.env` before  running the Dockerfile.  This solved my issue with this same error.
